const express = require('express');
const db = require('../db/db');
const { requireAuth } = require('../middleware/auth');
const PDFDocument = require('pdfkit');
const router = express.Router();

// GET /api/expenses
router.get('/', requireAuth, (req, res) => {
    const { from, to, category } = req.query;
    let query = 'SELECT * FROM expenses WHERE user_id = ?';
    const params = [req.session.user.id];

    if (from) { query += ' AND date >= ?'; params.push(from); }
    if (to) { query += ' AND date <= ?'; params.push(to); }
    if (category) { query += ' AND category = ?'; params.push(category); }

    query += ' ORDER BY date DESC';
    res.json(db.prepare(query).all(...params));
});

// POST /api/expenses
router.post('/', requireAuth, (req, res) => {
    const { title, category, amount, note, date } = req.body;
    if (!title || !amount) return res.status(400).json({ error: 'title and amount required' });

    const validCategories = ['electricity', 'fuel', 'rent', 'salary', 'other'];
    const cat = validCategories.includes(category) ? category : 'other';

    const result = db.prepare(
        'INSERT INTO expenses (user_id, title, category, amount, note, date) VALUES (?, ?, ?, ?, ?, ?)'
    ).run(req.session.user.id, title, cat, parseFloat(amount), note || null, date || new Date().toISOString().slice(0, 10));

    res.json({ ok: true, id: result.lastInsertRowid });
});

// PUT /api/expenses/:id
router.put('/:id', requireAuth, (req, res) => {
    const { title, category, amount, note, date } = req.body;
    if (!title || !amount) return res.status(400).json({ error: 'title and amount required' });

    const expId = parseInt(req.params.id);
    const validCategories = ['electricity', 'fuel', 'rent', 'salary', 'other'];
    const cat = validCategories.includes(category) ? category : 'other';

    const exp = db.prepare('SELECT id FROM expenses WHERE id = ? AND user_id = ?').get(expId, req.session.user.id);
    if (!exp) return res.status(404).json({ error: 'Expense not found' });

    db.prepare(`
        UPDATE expenses 
        SET title = ?, category = ?, amount = ?, note = ?, date = ? 
        WHERE id = ? AND user_id = ?
    `).run(title, cat, parseFloat(amount), note || null, date || new Date().toISOString().slice(0, 10), expId, req.session.user.id);

    res.json({ ok: true });
});

// DELETE /api/expenses/:id
router.delete('/:id', requireAuth, (req, res) => {
    const expId = parseInt(req.params.id);
    const exp = db.prepare('SELECT id FROM expenses WHERE id = ? AND user_id = ?').get(expId, req.session.user.id);
    if (!exp) return res.status(404).json({ error: 'Expense not found' });
    db.prepare('DELETE FROM expenses WHERE id = ?').run(expId);
    res.json({ ok: true });
});

// GET /api/expenses/pdf — export filtered expenses as PDF
router.get('/pdf', requireAuth, (req, res) => {
    const { from, to, category } = req.query;
    let query = 'SELECT * FROM expenses WHERE user_id = ?';
    const params = [req.session.user.id];

    if (from) { query += ' AND date >= ?'; params.push(from); }
    if (to) { query += ' AND date <= ?'; params.push(to); }
    if (category) { query += ' AND category = ?'; params.push(category); }
    query += ' ORDER BY date ASC';

    const expenses = db.prepare(query).all(...params);
    const user = db.prepare('SELECT name FROM users WHERE id = ?').get(req.session.user.id);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="expenses-report.pdf"');

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('Expenses Report', { align: 'center' });
    doc.fontSize(11).font('Helvetica').fillColor('#555')
        .text(`Generated by: ${user ? user.name : 'Unknown'}  |  Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
    if (from || to) {
        doc.text(`Period: ${from || 'All'} → ${to || 'Now'}`, { align: 'center' });
    }
    doc.moveDown(1);

    // Table header
    const cols = { date: 50, category: 130, title: 230, amount: 430, note: 490 };
    doc.fillColor('#000').font('Helvetica-Bold').fontSize(10);
    doc.text('Date', cols.date, doc.y);
    const headerY = doc.y - 12;
    doc.text('Category', cols.category, headerY);
    doc.text('Title', cols.title, headerY);
    doc.text('Amount', cols.amount, headerY);
    doc.moveDown(0.4);

    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#333').stroke();
    doc.moveDown(0.4);

    // Rows
    let totalAmount = 0;
    doc.font('Helvetica').fontSize(9).fillColor('#000');

    for (const exp of expenses) {
        const y = doc.y;
        doc.text(exp.date, cols.date, y, { width: 75 });
        doc.text(exp.category.charAt(0).toUpperCase() + exp.category.slice(1), cols.category, y, { width: 95 });
        doc.text(exp.title, cols.title, y, { width: 195 });
        doc.text(`Rs. ${parseFloat(exp.amount).toFixed(2)}`, cols.amount, y, { width: 80, align: 'right' });
        doc.moveDown(0.15);
        if (exp.note) {
            doc.fontSize(8).fillColor('#666').text(`  Note: ${exp.note}`, cols.title, doc.y, { width: 300 });
            doc.fillColor('#000').fontSize(9);
        }
        doc.moveDown(0.3);
        totalAmount += parseFloat(exp.amount);

        if (doc.y > 720) doc.addPage();
    }

    // Totals
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#333').stroke();
    doc.moveDown(0.5);
    doc.font('Helvetica-Bold').fontSize(11).fillColor('#000')
        .text(`Total: Rs. ${totalAmount.toFixed(2)}`, { align: 'right' });

    doc.end();
});

module.exports = router;
