const express = require('express');
const expenseService = require('../services/ExpenseService');
const { requireAuth } = require('../middleware/auth');
const PDFDocument = require('pdfkit');
const router = express.Router();
const db = require('../db/knex');

// GET /api/expenses
router.get('/', requireAuth, async (req, res) => {
    const expenses = await expenseService.listExpenses(req.session.user.shop_id, req.query);
    res.json(expenses);
});

// POST /api/expenses
router.post('/', requireAuth, async (req, res) => {
    const id = await expenseService.createExpense(req.body, req.session.user.shop_id, req.session.user.id);
    res.json({ ok: true, id });
});

// PUT /api/expenses/bulk
router.put('/bulk', requireAuth, async (req, res) => {
    const { expenses } = req.body;
    if (!expenses || !Array.isArray(expenses)) return res.status(400).json({ error: 'expenses array required' });
    
    await db.transaction(async (trx) => {
        for (const e of expenses) {
            await expenseService.updateExpense(e.id, e, req.session.user.shop_id);
        }
    });
    res.json({ ok: true });
});

// PUT /api/expenses/:id
router.put('/:id', requireAuth, async (req, res) => {
    await expenseService.updateExpense(req.params.id, req.body, req.session.user.shop_id);
    res.json({ ok: true });
});

// DELETE /api/expenses/:id
router.delete('/:id', requireAuth, async (req, res) => {
    await expenseService.deleteExpense(req.params.id, req.session.user.shop_id);
    res.json({ ok: true });
});

// GET /api/expenses/pdf
router.get('/pdf', requireAuth, async (req, res) => {
    const expenses = await expenseService.listExpenses(req.session.user.shop_id, req.query);
    const shop = await db('shops').where({ id: req.session.user.shop_id }).first();
    const user = req.session.user;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="expenses-report.pdf"');
    
    const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
    doc.pipe(res);

    const addFooter = () => {
        const range = doc.bufferedPageRange();
        for (let i = range.start; i < range.start + range.count; i++) {
            doc.switchToPage(i);
            const bottom = doc.page.height - 50;
            doc.moveTo(50, bottom - 10).lineTo(545, bottom - 10).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
            doc.fontSize(8).fillColor('#9ca3af').text(`Page ${i + 1} of ${range.count}`, 50, bottom, { align: 'right', width: 495 });
            doc.text('This is a secure, system-generated financial document.', 50, bottom, { align: 'left' });
        }
    };

    if (shop) doc.fontSize(28).font('Helvetica-Bold').fillColor('#111827').text(shop.name.toUpperCase(), { align: 'center' });
    doc.fontSize(14).font('Helvetica').fillColor('#4b5563').text('EXPENSES REPORT', { align: 'center', characterSpacing: 1 });
    doc.moveDown(0.5).fontSize(9).fillColor('#9ca3af').text(`GENERATED BY: ${user.name.toUpperCase()}   |   DATE: ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(1.5).moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').lineWidth(0.5).stroke().moveDown(2);

    const cols = { date: 50, category: 130, title: 210, amount: 460 };
    doc.fontSize(8).font('Helvetica-Bold').fillColor('#6b7280').text('DATE', cols.date, doc.y).text('CATEGORY', cols.category, doc.y).text('DESCRIPTION', cols.title, doc.y).text('AMOUNT (RS.)', cols.amount, doc.y, { align: 'right', width: 85 });
    doc.moveDown(0.4).moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#4f46e5').lineWidth(1).stroke().moveDown(0.2);

    let totalAmount = 0, rowIdx = 0;
    for (const exp of expenses) {
        if (doc.y > 740) doc.addPage();
        const y = doc.y; if (rowIdx % 2 === 0) doc.rect(50, y - 2, 495, 14).fill('#f3f4f6');
        doc.fillColor('#374151').font('Helvetica').fontSize(9).text(exp.date, cols.date, y).text(exp.category.toUpperCase(), cols.category, y).text(exp.title, cols.title, y, { width: 240 }).fillColor('#111827').font('Helvetica-Bold').text(parseFloat(exp.amount).toLocaleString(undefined, { minimumFractionDigits: 2 }), cols.amount, y, { align: 'right', width: 85 });
        doc.moveDown(0.8); totalAmount += parseFloat(exp.amount); rowIdx++;
    }
    doc.moveDown(1).font('Helvetica-Bold').fontSize(11).fillColor('#000').text(`TOTAL EXPENSES: RS. ${totalAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })}`, { align: 'right' });
    addFooter(); doc.end();
});

module.exports = router;
