CREATE TABLE IF NOT EXISTS shops (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT DEFAULT 'active',
  allowed_panels TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  logo_path TEXT,
  receipt_header_text TEXT,
  receipt_phone TEXT,
  receipt_address TEXT,
  receipt_images_json TEXT,
  receipt_policies TEXT,
  use_logo_on_receipt INTEGER DEFAULT 1,
  header_font_size INTEGER DEFAULT 18,
  header_font_weight TEXT DEFAULT 'bold',
  header_spacing INTEGER DEFAULT 10,
  contact_font_size INTEGER DEFAULT 10,
  contact_align TEXT DEFAULT 'center',
  contact_padding INTEGER DEFAULT 10,
  footer_font_size INTEGER DEFAULT 9,
  footer_font_style TEXT DEFAULT 'normal',
  footer_margin INTEGER DEFAULT 10,
  divider_style TEXT DEFAULT 'dashed',
  divider_width INTEGER DEFAULT 1,
  section_gap INTEGER DEFAULT 10,
  auto_calculate_damage_to_loss INTEGER DEFAULT 1,
  receipt_font_family TEXT DEFAULT 'monospace',
  shop_type TEXT DEFAULT 'retail',
  receipt_extended_name TEXT,
  extended_name_font_size INTEGER DEFAULT 10,
  extended_name_font_weight TEXT DEFAULT 'normal',
  extended_name_spacing INTEGER DEFAULT 2,
  use_text_on_receipt INTEGER DEFAULT 1,
  bill_printer TEXT
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL,
  type TEXT NOT NULL DEFAULT '1_month',
  start_date DATE DEFAULT CURRENT_DATE,
  end_date DATE,
  month TEXT NOT NULL,
  paid_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER REFERENCES shops(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  status TEXT DEFAULT 'active',
  allowed_panels TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  panel_permissions TEXT
);

CREATE TABLE IF NOT EXISTS brands (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  printer_station TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS expense_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  emoji TEXT DEFAULT '',
  color_class TEXT DEFAULT 'bg-slate-700 text-slate-300',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  sku TEXT NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  brand_id INTEGER NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  buying_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  stock INTEGER NOT NULL DEFAULT 0,
  min_stock_level INTEGER NOT NULL DEFAULT 0,
  is_deleted INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  selling_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_component INTEGER DEFAULT 0,
  damage_stock INTEGER NOT NULL DEFAULT 0,
  recovered_damage_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  manual_damage_loss DOUBLE PRECISION NOT NULL DEFAULT 0,
  recovered_damage_quantity INTEGER NOT NULL DEFAULT 0,
  image_path TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  buying_price DOUBLE PRECISION NOT NULL,
  quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  damaged_quantity DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS product_compositions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  component_product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  custom_name TEXT,
  quantity INTEGER NOT NULL DEFAULT 1,
  price DOUBLE PRECISION,
  cost DOUBLE PRECISION DEFAULT 0
);

CREATE TABLE IF NOT EXISTS floors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tables (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  table_number TEXT NOT NULL,
  capacity INTEGER DEFAULT 4,
  status TEXT DEFAULT 'available',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  floor_id INTEGER REFERENCES floors(id)
);

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  address TEXT,
  notes TEXT,
  credit_limit DOUBLE PRECISION DEFAULT 0,
  current_balance DOUBLE PRECISION DEFAULT 0,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sales (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id),
  customer_name TEXT DEFAULT '',
  customer_phone TEXT DEFAULT '',
  total DOUBLE PRECISION NOT NULL DEFAULT 0,
  discount DOUBLE PRECISION NOT NULL DEFAULT 0,
  tax_percentage DOUBLE PRECISION NOT NULL DEFAULT 0,
  payment_method TEXT NOT NULL DEFAULT 'cash',
  amount_received DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  customer_id INTEGER REFERENCES customers(id),
  delivery_address TEXT DEFAULT '',
  order_type TEXT DEFAULT 'dine_in',
  order_status TEXT DEFAULT 'pending',
  table_id INTEGER REFERENCES tables(id),
  waiter_id INTEGER REFERENCES users(id),
  rider_id INTEGER REFERENCES users(id),
  guest_count INTEGER DEFAULT 1,
  token_number TEXT,
  special_instructions TEXT,
  kitchen_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS sale_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id),
  parent_id INTEGER REFERENCES products(id),
  custom_name TEXT,
  quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
  price_at_sale DOUBLE PRECISION NOT NULL DEFAULT 0,
  buying_price_at_sale DOUBLE PRECISION NOT NULL DEFAULT 0,
  batch_id INTEGER REFERENCES product_batches(id),
  special_instructions TEXT,
  variants_json TEXT,
  addons_json TEXT
);

CREATE TABLE IF NOT EXISTS returns (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id),
  total_refund DOUBLE PRECISION NOT NULL DEFAULT 0,
  reason TEXT,
  payment_method TEXT NOT NULL DEFAULT 'cash',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS return_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id INTEGER NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id),
  quantity DOUBLE PRECISION NOT NULL DEFAULT 1,
  refund_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  buying_price_at_sale DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_damage INTEGER NOT NULL DEFAULT 0,
  sale_item_id INTEGER REFERENCES sale_items(id)
);

CREATE TABLE IF NOT EXISTS customer_ledger (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  sale_id INTEGER REFERENCES sales(id),
  type TEXT NOT NULL DEFAULT 'sale',
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  balance_after DOUBLE PRECISION NOT NULL DEFAULT 0,
  note TEXT,
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS expenses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'other',
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  note TEXT,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS brand_expense_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id INTEGER NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  month TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS raw_stocks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  unit TEXT NOT NULL,
  current_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
  min_stock_level DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_deleted INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  conversion_factor DOUBLE PRECISION NOT NULL DEFAULT 1,
  usage_unit TEXT
);

CREATE TABLE IF NOT EXISTS raw_stock_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_stock_id INTEGER NOT NULL REFERENCES raw_stocks(id) ON DELETE CASCADE,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  buying_price DOUBLE PRECISION NOT NULL,
  quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_stock_waste (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_stock_id INTEGER NOT NULL REFERENCES raw_stocks(id) ON DELETE CASCADE,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id),
  quantity DOUBLE PRECISION NOT NULL,
  reason TEXT,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS recipes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS recipe_ingredients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  raw_stock_id INTEGER NOT NULL REFERENCES raw_stocks(id) ON DELETE CASCADE,
  quantity DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS product_recipe_links (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  variant_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS support_tickets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL DEFAULT 'help',
  priority TEXT NOT NULL DEFAULT 'medium',
  subject TEXT NOT NULL,
  description TEXT NOT NULL,
  attachment_url TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ticket_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id INTEGER NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  comment TEXT NOT NULL,
  is_internal INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS activity_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  details TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_shop_id ON users(shop_id);
CREATE INDEX IF NOT EXISTS idx_products_shop_id ON products(shop_id);
CREATE INDEX IF NOT EXISTS idx_sales_shop_id ON sales(shop_id);
CREATE INDEX IF NOT EXISTS idx_expenses_shop_id ON expenses(shop_id);
CREATE INDEX IF NOT EXISTS idx_customers_shop_id ON customers(shop_id);
CREATE INDEX IF NOT EXISTS idx_brands_shop_id ON brands(shop_id);
CREATE INDEX IF NOT EXISTS idx_tables_shop_id ON tables(shop_id);
CREATE INDEX IF NOT EXISTS idx_returns_shop_id ON returns(shop_id);
CREATE INDEX IF NOT EXISTS idx_product_batches_shop_id ON product_batches(shop_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_shop_id ON activity_logs(shop_id);
CREATE INDEX IF NOT EXISTS idx_raw_stocks_shop_id ON raw_stocks(shop_id);
CREATE INDEX IF NOT EXISTS idx_raw_stock_batches_shop_id ON raw_stock_batches(shop_id);
CREATE INDEX IF NOT EXISTS idx_recipes_shop_id ON recipes(shop_id);

CREATE INDEX IF NOT EXISTS idx_sale_items_sale_id ON sale_items(sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_product_id ON sale_items(product_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_batch_id ON sale_items(batch_id);
CREATE INDEX IF NOT EXISTS idx_return_items_return_id ON return_items(return_id);
CREATE INDEX IF NOT EXISTS idx_return_items_sale_item_id ON return_items(sale_item_id);
CREATE INDEX IF NOT EXISTS idx_product_batches_product_id ON product_batches(product_id);
CREATE INDEX IF NOT EXISTS idx_customer_ledger_customer_id ON customer_ledger(customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_customer_id ON sales(customer_id);
CREATE INDEX IF NOT EXISTS idx_recipe_ingredients_recipe_id ON recipe_ingredients(recipe_id);
CREATE INDEX IF NOT EXISTS idx_product_recipe_links_product_id ON product_recipe_links(product_id);

CREATE INDEX IF NOT EXISTS idx_sales_created_at ON sales(created_at);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(date);
CREATE INDEX IF NOT EXISTS idx_customer_ledger_created_at ON customer_ledger(created_at);

CREATE TABLE IF NOT EXISTS discounts (
  id SERIAL PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'percentage', -- percentage, amount
  value DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS taxes (
  id SERIAL PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  percentage DOUBLE PRECISION NOT NULL DEFAULT 0,
  linked_payment_method TEXT, -- cash, card, online
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS print_queue (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  station_name TEXT NOT NULL,
  content_json TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_print_queue_shop_id ON print_queue(shop_id);
CREATE INDEX IF NOT EXISTS idx_print_queue_status ON print_queue(status);

CREATE TABLE IF NOT EXISTS printers (
  id SERIAL PRIMARY KEY,
  shop_id INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  display_name TEXT NOT NULL,
  system_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_printers_shop_id ON printers(shop_id);

